version: AV_{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
clone_depth: 1
before_build:
- cmd: >-
    git submodule update --recursive --init

    cd Source

    nuget restore

    cd ..
build:
  project: Source\AlephNote.sln
  verbosity: normal
