# Setup
title:        AlephNote
tagline:      An extensible, lightweight desktop note client for multiple backends
baseurl:      "/Mikescher/AlephNote"
paginate:     1

# About/contact
author:
  name:       Mike Schwörer
  url:        http://mikescher.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
